platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Flutter SDK'nın tam yolu (which flutter çıktından türetilmiş)
flutter_root = '/Users/nidalsancak/development/flutter'
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

# Firebase/Google pods ile uyum için static frameworks
use_frameworks! :linkage => :static

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)

  # Modül başlık/Swift import sorunlarını önlemek için
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['DEFINES_MODULE'] = 'YES'
      config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end